<?php

/**
 * Created by PhpStorm.
 * User: eotin
 * Date: 11/1/2016
 * Time: 10:31 AM
 */

namespace AppBundle\Constant;

class PhpReportConstant
{
    // Columns
    CONST COLUMNS_SITE = 'REPORT.COLUMNS.SITE';
    CONST COLUMNS_EXPECTED_REPORTS = 'REPORT.COLUMNS.EXPECTED_REPORTS';
    CONST COLUMNS_REPORTS_RECEIVED = 'REPORT.COLUMNS.REPORTS_RECEIVED';
    CONST COLUMNS_REPORTS_VALIDATED = 'REPORT.COLUMNS.REPORTS_VALIDATED';
    CONST COLUMNS_REPORTS_REJECTED = 'REPORT.COLUMNS.REPORTS_REJECTED';
    CONST COLUMNS_REPORTS_PENDING = 'REPORT.COLUMNS.REPORTS_PENDING';
    CONST COLUMNS_REPORTS_NEVER_RECEIVED = 'REPORT.COLUMNS.REPORTS_NEVER_RECEIVED';
    CONST COLUMNS_REPORTS_RECEIVED_ON_TIME = 'REPORT.COLUMNS.REPORTS_RECEIVED_ON_TIME';
    CONST COLUMNS_COMPLETENESS_PERCENT = 'REPORT.COLUMNS.COMPLETENESS_PERCENT';
    CONST COLUMNS_TIMELINESS_PERCENT = 'REPORT.COLUMNS.TIMELINESS_PERCENT';
    CONST COLUMNS_GLOBAL_PERFORMANCE = 'REPORT.COLUMNS.GLOBAL_PERFORMANCE';
    CONST COLUMNS_TOTAL_PERIOD = 'REPORT.COLUMNS.TOTAL_PERIOD';
    CONST COLUMNS_WEEK = 'REPORT.COLUMNS.WEEK';
    CONST COLUMNS_MONTH = 'REPORT.COLUMNS.MONTH';
    CONST COLUMNS_ADDRESSED_REPORTS = 'REPORT.COLUMNS.ADDRESSED_REPORTS';
    CONST COLUMNS_REPORTS_RECEIVED_ADDRESSED_ON_TIME = 'REPORT.COLUMNS.REPORTS_RECEIVED_ADDRESSED_ON_TIME';
    CONST COLUMNS_LAST_REPORT_RECEIVED = 'REPORT.COLUMNS.LAST_REPORT_RECEIVED';
    CONST COLUMNS_HEALTH_FACILITY_PARTICIPATING = 'REPORT.COLUMNS.HEALTH_FACILITY_PARTICIPATING';
    CONST COLUMNS_LAST_MESSAGE_SENT = 'REPORT.COLUMNS.LAST_MESSAGE_SENT';
    CONST COLUMNS_NUMBER_OF_MESSAGES_SENT = 'REPORT.COLUMNS.NUMBER_OF_MESSAGES_SENT';
    CONST COLUMNS_ALERT_PREFERRED_GATEWAY = 'REPORT.COLUMNS.ALERT_PREFERRED_GATEWAY';
    CONST COLUMNS_ALERT_PREFERRED_GATEWAY_SOURCE = 'REPORT.COLUMNS.ALERT_PREFERRED_GATEWAY_SOURCE';

    // Variables
    CONST SUM_TWIG = 'REPORT.VARIABLE.SUM_TWIG';

    // Report Titles
    CONST Weekly_Completeness_And_Timeliness = 'Weekly Completeness And Timeliness';
    CONST Monthly_Completeness_And_Timeliness = 'Monthly Completeness And Timeliness';
    CONST Weekly_Reports = 'Weekly Reports';
    CONST Monthly_Reports = 'Monthly Reports';
    CONST Number_of_Reports = 'Number of Reports';
    CONST Number_of_Cases_per_Disease_per_Week = 'Number of Cases per Disease per Week';
    CONST Number_of_Cases_per_Disease_per_Month = 'Number of Cases per Disease per Month';
    CONST Evolution_of_Completeness_And_Timeliness_per_Month = 'Evolution of Completeness And Timeliness per Month';
    CONST Evolution_of_Completeness_And_Timeliness_per_Week = 'Evolution of Completeness And Timeliness per Week';
    CONST SMS_Traffic_per_Gateway_per_Week = 'SMS Traffic per Gateway per Week';

    // Words
    CONST WORD_WEEK = 'REPORT.WORD.WEEK';

    // Chart
    CONST CHART_CASES = 'REPORT.CHART.CASES';
    CONST CHART_WEEK = 'REPORT.CHART.WEEK';
    CONST CHART_MONTH = 'REPORT.CHART.MONTH';
    CONST CHART_SITE = 'REPORT.CHART.SITE';
    CONST CHART_EPIDEMIOLOGIC_WEEK = 'REPORT.CHART.EPIDEMIOLOGIC_WEEK';
    CONST CHART_EVENT_NUMBER = 'REPORT.CHART.EVENT_NUMBER';
    CONST CHART_SMS = 'REPORT.CHART.SMS';

    // Level of hierarchy
    CONST COLUMNS_LEVEL_COUNTRY = 'REPORT.COLUMNS.LEVEL.COUNTRY';

    // Contact
    CONST CONTACT_ID = 'REPORT.COLUMNS.CONTACT.ID';
    CONST CONTACT_NAME = 'REPORT.COLUMNS.CONTACT.NAME';
    CONST CONTACT_TYPE = 'REPORT.COLUMNS.CONTACT.TYPE';
    CONST CONTACT_PHONE_NUMBER = 'REPORT.COLUMNS.CONTACT.PHONE_NUMBER';
    CONST CONTACT_EMAIL = 'REPORT.COLUMNS.CONTACT.EMAIL';
    CONST CONTACT_NOTE = 'REPORT.COLUMNS.CONTACT.NOTE';
    CONST CONTACT_LATITUDE = 'REPORT.COLUMNS.CONTACT.LATITUDE';
    CONST CONTACT_LONGITUDE = 'REPORT.COLUMNS.CONTACT.LONGITUDE';
    CONST CONTACT_LOCATION_DATE = 'REPORT.COLUMNS.CONTACT.LOCATION_DATE';
    CONST CONTACT_IMEI = 'REPORT.COLUMNS.CONTACT.IMEI';

    // Description
    CONST DESCRIPTION_HEALTH_FACILITY_PARTICIPATING = 'REPORT.DESCRIPTION.HEALTH_FACILITY_PARTICIPATING';
}