<?php
/**
 * Contact Service
 *
 * @author François Cardinaux
 */

namespace AppBundle\Services;

use AppBundle\Entity\SesDashboardReportDataSource;
use AppBundle\Repository\RepositoryInterface;
use AppBundle\Repository\SesDashboardContactRepository;
use AppBundle\Repository\SesDashboardReportDataSourceRepository;
use Symfony\Bridge\Monolog\Logger;

class ReportDataSourceService extends BaseRepositoryService
{
    /**
     * @var SesDashboardReportDataSourceRepository
     */
    private $reportDataSourceRepository;

    public function __construct(Logger $logger, SesDashboardReportDataSourceRepository $reportDataSourceRepository)
    {
        parent::__construct($logger);
        $this->reportDataSourceRepository = $reportDataSourceRepository;
    }

    /**
     * @return SesDashboardReportDataSource[]
     */
    public function findAll()
    {
        return parent::findAll();
    }

    /**
     * @param $id
     * @return SesDashboardReportDataSource|null
     */
    public function findOneById($id)
    {
        return parent::findOneById($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $code
     * @return SesDashboardReportDataSource[]
     */
    public function findByCode($code) {
        return $this->reportDataSourceRepository->findByCode($code);
    }

    /**
     * @return RepositoryInterface|SesDashboardContactRepository|SesDashboardReportDataSourceRepository
     */
    public function getRepository()
    {
        return $this->reportDataSourceRepository;
    }

    /**
     * @param RepositoryInterface $repository
     */
    public function setRepository(RepositoryInterface $repository)
    {
        $this->reportDataSourceRepository = $repository;
    }
}