<?php
/**
 * Created by PhpStorm.
 * User: nfargere
 * Date: 23-Aug-18
 * Time: 11:45
 */

namespace AppBundle\Tests\Utils;


use AppBundle\Tests\BaseKernelTestCase;
use AppBundle\Utils\Helper;

class HelperTest extends BaseKernelTestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCleanForReference() {
        $cleanedText = Helper::cleanForReference("Test Héllo");
        $this->assertEquals('Test Hello', $cleanedText);
    }

    public function testCleanForFileName() {
        $cleanedText = Helper::cleanForFileName("Test Héllo");
        $this->assertEquals('Test_Hello', $cleanedText);
    }
}